SELECT * FROM CATEGORIES
SELECT * FROM CUSTOMERS
SELECT * FROM EMPLOYEES
SELECT * FROM ORDER_DETAILS
SELECT * FROM ORDERS
SELECT * FROM PRODUCT_VENDORS
SELECT * FROM PRODUCTS
SELECT * FROM VENDORS



--1.Знайдіть середню кількість одиниць товару в кожному замовлені.
SELECT ORDERNUMBER, AVG(QUANTITYORDERED) AS AVG_QUANTITYORDERED
FROM ORDER_DETAILS
GROUP BY ORDERNUMBER
ORDER BY ORDERNUMBER

--2.Яка сума найбільшого замовлення?
SELECT TOP 1 ORDERNUMBER, SUM(QUOTEDPRICE*QUANTITYORDERED) AS ORDERSUM
FROM ORDER_DETAILS
GROUP BY ORDERNUMBER
ORDER BY ORDERSUM DESC

--3.Клієнтів з якого міста в компанії найбільше?
SELECT TOP 1 CUSTCITY FROM ORDERS AS O
JOIN CUSTOMERS AS C
ON O.CUSTOMERID = C.CUSTOMERID
GROUP BY CUSTCITY
ORDER BY COUNT(C.CUSTOMERID) DESC

--4.Який офіс (з якого міста) дає компанії найбільші прибутки?
SELECT TOP 1 VENDCITY, SUM(QUOTEDPRICE - WHOLESALEPRICE) AS PROFIT
FROM PRODUCTS AS P
INNER JOIN PRODUCT_VENDORS AS PV
ON P.PRODUCTNUMBER = PV.PRODUCTNUMBER
INNER JOIN VENDORS AS V
ON PV.VENDORID = V.VENDORID
INNER JOIN ORDER_DETAILS AS OD
ON P.PRODUCTNUMBER = OD.PRODUCTNUMBER
GROUP BY VENDCITY
ORDER BY PROFIT DESC

--5.Який продукт з асортименту товарів купують найбільше?
SELECT TOP 1 P.PRODUCTNAME, SUM(O.QUANTITYORDERED) AS SUM_QUANTITYORDERED
FROM ORDER_DETAILS AS O
INNER JOIN PRODUCTS AS P
ON O.PRODUCTNUMBER = P.PRODUCTNUMBER
GROUP BY P.PRODUCTNAME
ORDER BY SUM_QUANTITYORDERED DESC

--6.Виведіть перелік замовлень, які доставлялись клієнтам довше 5 днів.
SELECT * FROM ORDERS
WHERE DATEDIFF(DAY, ORDERDATE, SHIPDATE) > 5

--7.Визначте товари, яких немає в наявності. Які з цих товарів можуть бути доставлені на склад за 4 дні?
SELECT * FROM PRODUCTS AS P
INNER JOIN PRODUCT_VENDORS AS PV
ON P.PRODUCTNUMBER = PV.PRODUCTNUMBER
WHERE DAYSTODELIVERY <= 4 AND QUANTITYONHAND = 0

--8.Визначте товар, від продажу одиниці якого чистий прибуток фірми є найбільшим.
SELECT TOP 1 PRODUCTNAME, MAX(RETAILPRICE - WHOLESALEPRICE) AS MAX_PROFIT
FROM PRODUCTS AS P
INNER JOIN PRODUCT_VENDORS AS PV
ON P.PRODUCTNUMBER = PV.PRODUCTNUMBER
GROUP BY PRODUCTNAME
ORDER BY MAX_PROFIT DESC

--9.Знайдіть всіх клієнтів, прізвище яких починається з літери «D» та які живуть в Портленді.
SELECT * FROM CUSTOMERS
WHERE CUSTLASTNAME LIKE 'D%' AND CUSTCITY = 'Portland'
